### PR TITLE
Styles for the Cards component

### PR DESCRIPTION
**Pull request by briansaycocie**
This is based off of [Bootstrap's Cards component](https://v4-alpha.getbootstrap.com/components/card/) customized to fit JDRF. The Card styles match up to the comps in Zeplin. For HTML and instructions on usage, check out this PR: #77

### CODE REVIEW

**Comment by fuhton** [comment]
@RachelRVasquez Would love your input on this

**Comment by RachelRVasquez** [comment]
@fuhton It's looking good to me. I'd like to confirm with @briansaycocie whether card decks display well as this looks like a great built in tool to take advantage of for varying heights:

http://v4-alpha.getbootstrap.com/components/card/#decks

I'd also like to keep in mind that flexbox isn't going to work in IE9:

http://v4-alpha.getbootstrap.com/getting-started/flexbox/#browser-support

But if we can get flexibility hooked up from this task, https://github.com/JDRF/design-system/issues/58 then we can test this again for Flexbox issues.

**Comment by fuhton** [comment]
@RachelRVasquez We're future proofing with the "enable-flex" checks. #58 is related to gh-pages only, not the master branch.

Also, I'd like to merge in the work and enhance from there. Thoughts?

**Comment by RachelRVasquez** [comment]
@fuhton Agreed. Let's merge in and enhance later.

**Pull request merged**
